### PR TITLE
add support for Form::MIN and Form::MAX rules

### PR DESCRIPTION
**Pull request by Ciki**
extended support of Form rules, in addition to Form::RANGE

### CODE REVIEW

**Comment by hrach** [comment]
Thank you!

**Comment by Ciki** [comment]
@hrach thank you. can you please issue new tag/release?

**Comment by Ciki** [comment]
@hrach would you consider issuing new tag/release please?

**Comment by hrach** [comment]
done

**Comment by Ciki** [comment]
thanks!

**Pull request merged**
