### PR TITLE
DateControl: custom time may be set

### PR DESCRIPTION
**Pull request by Ciki**
this update comes handy when DateControl is used for a dateTo filter which we usually want to contain 23:59:59 time to pass conditions against other dateTime objects 

proposed code change contains array unpacking feature which is present for since php7.4, so composer.json should be updated as well probably (no need to support older php versions I guess)

### CODE REVIEW

**Comment by hrach** [comment]
Sorry, not going to accept this. This is a form component, and bringing a domain logic to it doesn't seem a good idea.

**Comment by Ciki** [comment]
@hrach I see. However, we already call `->setTime` on datetime object when parsing and getting value.. this PR only allows default time to be set on the object.. now it's always 00:00:00

this is useful eg. in Form::MAX rule usage (as it's a form component)

**Comment by Ciki** [comment]
@hrach haven't you reconsidered this PR after my last comment explanation?

**Comment by hrach** [comment]
@Ciki setTime is called only because there is no PHP type represeting "just" a date. The most clean way is to set it to 00:00:00. Putting other time to this kind of form field makes it DateTime, not Date control. 

Maybe you could explain a bit more the validation issue you have and what are you traying to achieve.

**Comment by Ciki** [comment]
@hrach I see. I kindda struggle with the Date object design and its DateTime implementation. I agree Date should have only 00:00:00 time part but after a form submission in $onSuccess I get DateTime object and I would like to be able to change it once and use it in all other Form's $onSuccess calls(). Currently we force the 00:00:00 in the `getValue()`, maybe we could only set it within `getDefaultParser()` and not every time in `getValue()` (as in this PR)? what do you think?

**Comment by hrach** [comment]
getValue() has to return sanitized value every time. I guess the best way for you is to create custom form control that will behave as you wish.

**Comment by Ciki** [comment]
OK, thanks

**Pull request closed without merging**
